repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: check-json
      - id: check-merge-conflict
      - id: check-toml
      - id: check-xml
      - id: check-yaml
      - id: end-of-file-fixer
      - id: mixed-line-ending
        args: [ --fix=no ]
      - id: pretty-format-json
        args:
          - --indent=4
          - --autofix
      - id: trailing-whitespace
        args: [ --markdown-linebreak-ext=md ]
- repo: https://github.com/compilerla/conventional-pre-commit
  rev: v2.0.0
  hooks:
    - id: conventional-pre-commit
      stages: [commit-msg]
      args: []
- repo: https://github.com/Lucas-C/pre-commit-hooks
  rev: v1.3.1
  hooks:
    - id: forbid-crlf
    - id: remove-crlf
    - id: forbid-tabs
    - id: remove-tabs
- repo: https://github.com/adrienverge/yamllint
  rev: v1.27.1
  hooks:
    - id: yamllint
      args: [ --config=$(pwd)/.yamllint.yml ]
      stages: [commit-msg]
- repo: https://github.com/codespell-project/codespell
  rev: v2.2.1
  hooks:
    - id: codespell
      args: [ --config=$(pwd)/.codespell.yml ]
- repo: https://github.com/igorshubovych/markdownlint-cli
  rev: v0.32.1
  hooks:
    - id: markdownlint
- repo: https://github.com/Yelp/detect-secrets
  rev: v1.3.0
  hooks:
    - id: detect-secrets
- repo: https://github.com/sirosen/texthooks
  rev: 0.3.1
  hooks:
    - id: fix-smartquotes
    - id: fix-ligatures
    - id: forbid-bidi-controls
- repo: https://github.com/zricethezav/gitleaks
  rev: v8.2.0
  hooks:
    - id: gitleaks
