# Main HUGO Configuration for my website

## Set the baseurl to aliimami.com
baseURL = '//aliimami.com'

## Set theme to LoveIt (https://hugoloveit.com/)
theme = 'FixIt'

# Site title for ease of use
title = "Imamiland"

# A site subtitle
subtitle = "I talk about Life, R, Data Science, among other things"

# Add site description
description = "Imamiland is a personal blog by Ali Imami"

## Language settings
languageCode = 'en-us'
languageName = 'English'

# whether to use robots.txt
enableRobotsTXT = true

# whether to use emoji code
enableEmoji = true

## Set the default author
[author]
name = "Ali Sajid Imami"
link = "https://aliimami.com"
avatar = "/images/aliimami.png"
email = "hello@aliimami.com"

## Google Analytics Tracking ID
googleAnalyticsID = 'G-X1NZCWF97B'

# Copyright Description
# SPDX-FileCopyrightText: 2022 - 2024 Ali Sajid Imami
#
# SPDX-License-Identifier: MIT

copyright = "Copyright © Ali Sajid Imami 2022-2024"

# Tweak Parameters
[params]
## Default Theme
defaultTheme = "dark"
version = "0.3.14"

## Use sha512 for SRI
fingerprint = "sha512"

# Site description
description = "Imamiland is a personal blog by Ali Imami"

[params.header.title]
# URL of the LOGO
logo = ""
# title name
name = "Imamiland"
# you can add extra information before the name (HTML format is supported), such as icons
pre = ""
# you can add extra information after the name (HTML format is supported), such as icons
post = ""
# whether to use typeit animation for title name
typeit = false

[params.home.profile]
enable = true
# Gravatar Email for preferred avatar in home page
gravatarEmail = ""
# URL of avatar shown in home page
avatarURL = ""
# title shown in home page (HTML format is supported)
title = "Imamiland"
# subtitle shown in home page (HTML format is supported)
subtitle = "The musings of a grad student. \n Stranger in a strange land."
# whether to use typeit animation for subtitle
typeit = true
# whether to show social links
social = true
# disclaimer (HTML format is supported)
disclaimer = ""

[params.backToTop]
enable = true
scrollpercent = false

# Footer configuration
[params.footer]
since = 2022

# Set up an RSS feed
[params.feed]
limit = 10
fullText = true

[params.cookieconsent]
enable = true

# Section configuration
[params.section]
dateFormat = "Monday, January 2, 2006 3:04 PM EDT"

[params.social]
twitter = "doctor_no"
github = "AliSajid"
linkedin = "asimami"
keybase = "banseljaj"
googlescholar = "https://scholar.google.com/citations?user=tGIcYK4AAAAJ"
researchgate = "Ali-Imami"
orcid = "0000-0003-3684-3539"

[params.page]
[params.page.comment]
enable = true
[params.page.comment.disqus]
enable = true
shortname = "aliimami"

# Enable minification
[minify]
disableHTML = false
disableCSS = false
disableJS = false
disableJSON = false

# Markup configuration
[markup]
_merge = "shallow"
[markup.goldmark]
[markup.goldmark.extensions]
strikethrough = false
# https://gohugo.io/getting-started/configuration-markup/#extras
[markup.goldmark.extensions.extras]
[markup.goldmark.extensions.extras.delete]
enable = true
[markup.goldmark.extensions.extras.insert]
enable = true
[markup.goldmark.extensions.extras.mark]
enable = true
[markup.goldmark.extensions.extras.subscript]
enable = true
[markup.goldmark.extensions.extras.superscript]
enable = true
[markup.highlight]
noClasses = false

# Output Configuration
[outputs]
_merge = "shallow"

# Taxonomies Configuration
[taxonomies]
_merge = "shallow"

# Menu Configuration
[menu]
[[menu.main]]
weight = 1
identifier = "posts"
# you can add extra information before the name (HTML format is supported), such as icons
pre = ""
# you can add extra information after the name (HTML format is supported), such as icons
post = ""
name = "Posts"
url = "/posts/"
# title will be shown when you hover on this menu link
title = ""
[[menu.main]]
weight = 2
identifier = "tags"
pre = ""
post = ""
name = "Tags"
url = "/tags/"
title = ""
[[menu.main]]
weight = 3
identifier = "categories"
pre = ""
post = ""
name = "Categories"
url = "/categories/"
title = ""
[[menu.main]]
weight = 4
identifier = "about_me"
pre = ""
post = ""
name = "About Me"
url = "/about_me/"
title = "About Me"
