[tools]
go = "1.19"
hugo-extended = "0.160.1"
node = "24.14.1"
pnpm = "10.33.0"

[tasks]
start = "./scripts/manage_hugo.sh start"
restart = "./scripts/manage_hugo.sh restart"
stop = "./scripts/manage_hugo.sh stop"
status = "./scripts/manage_hugo.sh status"
