version = 1
SPDX-PackageName = "AliSajid.github.io"
SPDX-PackageSupplier = "Ali Sajid Imami <Ali.Sajid.Imami@gmail.com>"
SPDX-PackageDownloadLocation = "https://github.com/AliSajid/AliSajid.github.io"

[[annotations]]
path = [
  ".hugo_build.lock",
  ".mise.toml",
  ".pre-commit-config",
  ".prettierrc",
  ".secrets.baseline",
  ".vale.ini",
  ".markdownlint.json",
  ".codespellrc",
  ".codespell-ignore-words.txt",
  ".markdownlintignore",
  "renovate.json",
  ".gitleaksignore",
  ".secrets.baseline",
  ".pre-commit-config.yaml",
  "styles/config/**/*.txt",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "2021 - 2024 Ali Sajid Imami <Ali.Sajid.Imami@gmail.com>"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = ".github/workflows/**.yaml"
precedence = "aggregate"
SPDX-FileCopyrightText = "2021 - 2024 Ali Sajid Imami <Ali.Sajid.Imami@gmail.com>"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = [".gitignore", ".gitattributes", ".gitmodules"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2021 - 2024 Ali Sajid Imami <Ali.Sajid.Imami@gmail.com>"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = "REUSE.toml"
precedence = "aggregate"
SPDX-FileCopyrightText = "2021 - 2024 Ali Sajid Imami <Ali.Sajid.Imami@gmail.com>"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = "static/CNAME"
precedence = "aggregate"
SPDX-FileCopyrightText = "2021 - 2024 Ali Sajid Imami <Ali.Sajid.Imami@gmail.com>"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = [
  "content/**/*.md",
  "content/**/*.jpg",
  "content/**/*.png",
  "content/**/*.svg",
  "content/**/*.webp",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "2021 - 2024 Ali Sajid Imami <Ali.Sajid.Imami@gmail.com>"
SPDX-License-Identifier = "CC-BY-NC-SA-4.0"
